name: Build Packages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm

    - name: Build RPM
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cp count_files.sh ~/rpmbuild/SOURCES/
        cp packaging/rpm/counter.spec ~/rpmbuild/SPECS/
        rpmbuild -bb ~/rpmbuild/SPECS/counter.spec
        mkdir -p artifacts
        cp ~/rpmbuild/RPMS/noarch/*.rpm artifacts/

    - name: Build DEB
      run: |
        mkdir -p file-counter_1.0_all/usr/bin
        mkdir -p file-counter_1.0_all/DEBIAN
        cp count_files.sh file-counter_1.0_all/usr/bin/count_files
        chmod +x file-counter_1.0_all/usr/bin/count_files
        cp packaging/deb/control file-counter_1.0_all/DEBIAN/
        dpkg-deb --build file-counter_1.0_all
        cp file-counter_1.0_all.deb artifacts/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-packages
        path: artifacts/
